
import "HostViewModel.idl"; 

namespace DataBindingInDepth
{
    [default_interface]
    runtimeclass MainWindow : Microsoft.UI.Xaml.Window
    {
        MainWindow();

        HostViewModel ViewModel{ get; };
    }
}
